{
  "name": "next-custom-error-sandbox",
  "version": "1.0.0",
  "description": "An exploration of how next.js handles errors",
  "main": "index.js",
  "scripts": {
    "dev": "./node_modules/.bin/now dev",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "basic-auth": "^2.0.1",
    "next": "^11.1.3",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  },
  "devDependencies": {
    "now": "^16.1.2"
  }
}
